# tensorflow basics


In [2]:
import tensorflow as tf

tensor_zero_d = tf.constant(4)

print(tensor_zero_d)

tf.Tensor(4, shape=(), dtype=int32)


In [3]:
tensor_one_d = tf.constant([2,1,2])


print(tensor_one_d)

tf.Tensor([2 1 2], shape=(3,), dtype=int32)


In [4]:
tensor_two_d = tf.constant([
    [ 1,2,0],
    [1,2,4],
    [0,0,0]
])

print(tensor_two_d)

tf.Tensor(
[[1 2 0]
 [1 2 4]
 [0 0 0]], shape=(3, 3), dtype=int32)


In [5]:
tensor_3_d = tf.constant([
    [[1, 2, 0], [1, 2, 5]],  # First 2x3 matrix
    [[1, 2, 0], [1, 2, 5]]   # Second 2x3 matrix
])

print(tensor_3_d)

tf.Tensor(
[[[1 2 0]
  [1 2 5]]

 [[1 2 0]
  [1 2 5]]], shape=(2, 2, 3), dtype=int32)
